#!/bin/bash

# exit if already running
if [ $(ps cax | grep blurlock | wc -l) -gt 2 ]; then
        exit
fi


# take screenshot
scrot /tmp/scrot.png

# apply effect
#convert /tmp/scrot.png -blur 0x5 /tmp/scrot.png
#convert /tmp/scrot.png -scale 5% -scale %2000 /tmp/scrot.png
~/scripts/blurlock/xwobf /tmp/scrot.png

# set screen timeout to 30 sec
xset s 30

# use notify-send to show basic status info
while :
do 
	notify-send -t 10000 "$(date "+%F %R")" \
	"$(cat /sys/class/power_supply/BAT1/capacity)%, $(cat /sys/class/power_supply/BAT1/status)"
	sleep 10
done &

# run i3lock
i3lock -n -e -f -i /tmp/scrot.png

# disable screen timeout
xset s off

killall blurlock
