[theme]
theme = "native"

[theme.overrides]
good_fg = "#90bf6d"
warning_fg = "#ebc174"
critical_fg = "#e8696f"

[icons]
icons = "none"

[[block]]
block = "time"
format = " $timestamp.datetime(f:'%a %d.%m %R') "

[[block]]
block = "pomodoro"
notify_cmd = "notify-send '{msg}'"
message = "Pomodoro over!\nTake a break!"
break_message = "Break over!\nTime to work!"
[block.icons_overrides]
pomodoro = "POM"

[[block]]
block = "pacman"
interval = 3600
format = " UPD $pacman "

[[block]]
block = "sound"
step_width = 3
max_vol = 100
[[block.click]]
button = "left"
cmd = "pavucontrol -t 1"

[[block]]
block = "net"
device = "^wl"
format = " $device $signal_strength% $ssid $ip "
missing_format = ""
[[block.click]]
button = "left"
cmd = "nm-connection-editor"

[[block]]
block = "net"
device = "^(enp|eth)"
format = " $device $ip "
missing_format = ""
[[block.click]]
button = "left"
cmd = "nm-connection-editor"

[[block]]
block = "net"
device = "^wg"
format = " $device $ip "
missing_format = " wg "
[[block.click]]
button = "left"
cmd = "nm-connection-editor"

[[block]]
block = "net"
device = "^tun"
format = " $device $ip "
missing_format = ""
[[block.click]]
button = "left"
cmd = "nm-connection-editor"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
format = " $path: $available "
alert = 10
warning = 20

[[block]]
block = "battery"
format = " $icon $percentage "
full_format = " $icon FULL "
full_threshold = 95
[block.icons_overrides]
bat_charging = "CHR"

[[block]]
block = "memory"
format = " $icon $mem_avail "
interval = 5
warning_mem = 80
critical_mem = 95
[[block.click]]
button = "left"
cmd = "alacritty -e htop"

[[block]]
block = "cpu"
interval = 1
format = " $icon $utilization "
[[block.click]]
button = "left"
cmd = "alacritty -e htop"

[[block]]
block = "temperature"
format = " $icon $max "
chip = "*-isa-*"
