#!/bin/sh

export PATH="$HOME/scripts:$PATH"

################
#    CONFIG    #
################
bspc config border_width 1
bspc config window_gap 12
bspc config top_padding 22
bspc config focus_follows_pointer false
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_by_distance true

# COLOR
bspc config focused_border_color	"#00A2FF"
bspc config presel_feedback_color   "#00A2FF"


bspc monitor -d 1 2 3 4 5 6 7 8 9

# RULES
bspc rule -a firefox locked=on
bspc rule -a xfce4-mixer state=floating
bspc rule -a telegram-desktop state=floating
bspc rule -a simplescreenrecorder state=floating
bspc rule -a xfce4-panel state=floating
bspc rule -a /usr/lib/xfce4/panel/wrapper-1.0 state=floating
bspc rule -a gnuplot_qt state=floating
bspc rule -a Screenkey manage=off

# DESKTOP
bspc desktop 2 -l monocle
#################



#################
#   AUTOSTART   #
#################
feh --bg-scale ~/.config/bspwm/wallpaper    # set the wallpaper
xsetroot -cursor_name left_ptr	# set the default mouse cursor
sxhkd & # start the hotkey daemon
nm-applet &
compton -b
redshift -l 16:48 -t 6500:4500 &
xfsettingsd &
xfce4-panel -d &
xfce4-power-manager
/usr/bin/start-pulseaudio-x11 &
xautolock -locker blurlock -time 3 -corners 0-00 &
xset s off -dpms	# disbale screen blanking (already handled by blurlock)
export QT_STYLE_OVERRIDE=GTK+	# use GTK theme for Qt-Apps
#################
