#!/bin/bash

# change working directory 
cd $(dirname $1)

# save basnmae without extension
BASE=$(basename $1)
DOCNAME="${BASE%.*}"

# recompile pdf if .tex files change
mkpdf() {
	while inotifywait -qq --recursive -e modify -e create -e delete -e move --includei ".*\.tex$" --includei ".*\.bib$" .; do
		rubber -d $DOCNAME
	done
}

kill_mkpdf() {
	# when evince exits, kill mkpdf and clean directory
	kill $mkpdf_pid
	rubber --clean $DOCNAME
	[[ -f $DOCNAME.ent ]] && rm $DOCNAME.ent
	exit 0
}

# trap ctrl-c and call ctrl_c() to close cleanly
trap ctrl_c INT
ctrl_c() {
	kill_mkpdf
}

# start mkpdf() and save its PID
mkpdf & mkpdf_pid=$!

# starts evince pdf reader
evince $DOCNAME.pdf

# kill everything when evince dies
kill_mkpdf
