#!/bin/bash
DOCNAME="${1%.*}"

# remakes pdf if .tex files change
function mkpdf() {
	while inotifywait -r -qq -e modify -e create -e delete -e move --includei ".*\.tex" .; do
		rubber -d $DOCNAME
	done
}

# start mkpdf() and saves its PIID
mkpdf & mkpdf_pid=$!

# starts evince pdf reader
evince $DOCNAME.pdf

# when evince exits, kill mkpdf and clean directory
kill $mkpdf_pid
rubber --clean $DOCNAME
rm -f $DOCNAME.ent
