#!/bin/bash

# split user input at every colon
IFS=':' read -ra array <<< "$1"

# calculate the number of secs
case "${#array[@]}" in
	1) 	secs=${array[0]}
		format="%S"
		;;
	2)	secs=$(( ${array[0]} * 60 + ${array[1]} ))
		format="%M:%S"
		;;
	3)	secs=$(( ${array[0]} * 3600 + ${array[1]} * 60  + ${array[2]} ))
		format="%H:%M:%S"
		;;
esac

# run the countdown
date1=$((`date +%s` + $secs)); 
while [ "$date1" -ge `date +%s` ]; do 
	output="$(date -u --date @$(($date1 - `date +%s`)) +$format)"
	# output either with echo or as specified in the second argument
	[ -z "$2" ] && echo -en "$output\r"
	[ -n "$2" ] && clear && $2 $output
	sleep 0.1
done
