#!/bin/bash
spawndrop() {
    bspc rule -a Termite -o state=floating
    (termite --geometry=1520x480+200+23; rm /tmp/drop) &
    sleep 0.2
    bspc query -N -n focused > /tmp/drop
}

drop() {
    if bspc query -N -n $(cat /tmp/drop).hidden; then
        bspc node $(cat /tmp/drop).hidden -g hidden=off
        bspc node $(cat /tmp/drop) --to-desktop focused
        bspc node $(cat /tmp/drop) --focus
    else
        bspc node $(cat /tmp/drop).!hidden.floating -g hidden=on
    fi
}

if [[ -f /tmp/drop ]] && bspc query -N -n $(cat /tmp/drop).floating; then
    drop
else
    spawndrop
fi
