#!/bin/bash
spawndrop() {
    bspc rule -a Termite -o state=floating
    (termite --geometry=1522x482+199+23; bspc query -N -n "$(cat /tmp/drop)" || rm /tmp/drop) &
    sleep 0.2
    bspc query -N -n focused > /tmp/drop
}

drop() {
    if bspc query -N -n "$NODEID".hidden; then
        bspc node "$NODEID".hidden -g hidden=off
        bspc node "$NODEID" --to-desktop focused
        bspc node "$NODEID" --focus
    else
        bspc node "$NODEID".!hidden.floating -g hidden=on
    fi
}

readonly NODEID=$(cat /tmp/drop)
if [[ -f /tmp/drop ]] && bspc query -N -n "$NODEID".floating; then
    drop
else
    spawndrop
fi
