#!/usr/bin/env bash

# TODO
# security hardening (network especially)
# locale fix

install() {
	IGNORE="linux reiserfsprogs nano xfsprogs jfsutils cryptsetup lvm2 device-mapper usbutils mdadm pciutils licenses s-nail"
	PKG="$(join -v 1 <(pacman -Sgq base | sort) <(echo $IGNORE | tr " " "\n" | sort))"
	ADDPKG="sudo"
	pacstrap -cd $1 $PKG $ADDPKG --needed && touch $1/installed
}

configure() {
	# create config file
	echo -e "# See 'man systemd.nspawn' for all available options.\n" > $1.nspawn
	echo -e "[Exec]\nBoot=yes" >> $1.nspawn
	echo -e "[Files]\nBindReadOnly=/var/cache/pacman/pkg" >> $1.nspawn

	# set max journal size
	grep -q "^SystemMaxUse" $1/etc/systemd/journald.conf || 
		echo "SystemMaxUse=50M" >> $1/etc/systemd/journald.conf

	# set pacman Color and VerbosePkgLists Options
	sed -i '/^#Color/s/^#//' $1/etc/pacman.conf
	sed -i '/^#VerbosePkgLists/s/^#//' $1/etc/pacman.conf

	# allow %wheel to run sudo
	sed -i '/^# %wheel ALL=(ALL) ALL$/s/^# //' $1/etc/sudoers

	touch $1/configured
}

spawn() {
	systemd-nspawn --settings=trusted --directory=$1
}

# since the setting=trusted option must be used, the .nspawn file doesn't override the defaults. 
# The only unwanted default is removed here
[[ -f /etc/systemd/system/systemd-nspawn@.service ]] ||
	sed -e 's/--network-veth //g' /usr/lib/systemd/system/systemd-nspawn@.service > \
	/etc/systemd/system/systemd-nspawn@.service


if [[ -f $1/installed ]] && [[ -f $1/configured ]] && [[ -f $1.nspawn ]]; then
	spawn $1
else
	mkdir -p $1 && 
	([[ -f $1/installed ]] || install $1) && 
	(([[ -f $1/configured ]] && [[ -f $1.nspawn ]]) || configure $1) && 
	spawn $1
fi
